gpu: 0
mode: [preprocessing] # preprocessing, classic, train', test',inference
data_path: D:\Datasets\Gestures_updated
log_path: log
model_path: models
learning_rate: 0.0001
learning_rate_fusing_coefficient: 10
weight_decay: 0.0005
loss_type: MSE #L2, Smooth L1, MSE
epochs: 200
batch_size: 120
pretrained_image_model: False
pretrained_fusing_model: False
pretrained_image_model_path: models/model_hand_120.pth
pretrained_dots_model_path: models/model_dot_hand_120.pth
pretrained_fusing_model_path: models/model_fuzing_hand_120.pth
pretrained_image_model_require_grad: true
pretrained_dots_model_require_grad: true
pretrained_fusing_model_require_grad: true
